CREATE TYPE "public"."billing_interval" AS ENUM('monthly', 'yearly');--> statement-breakpoint
CREATE TYPE "public"."currency_code" AS ENUM('INR', 'USD');--> statement-breakpoint
CREATE TYPE "public"."plan_key" AS ENUM('pro', 'pro_plus', 'school');--> statement-breakpoint
CREATE TYPE "public"."subscription_status" AS ENUM('created', 'authenticated', 'active', 'pending', 'halted', 'cancelled', 'completed', 'expired');--> statement-breakpoint
CREATE TYPE "public"."article_scope" AS ENUM('national', 'international');--> statement-breakpoint
CREATE TYPE "public"."article_source" AS ENUM('newsdata_io', 'rbi_rss', 'pib_rss', 'sebi_rss');--> statement-breakpoint
CREATE TYPE "public"."article_status" AS ENUM('new', 'duplicate', 'used', 'skipped');--> statement-breakpoint
CREATE TYPE "public"."app_permission" AS ENUM('questions.create', 'questions.update', 'questions.delete', 'papers.import', 'users.read');--> statement-breakpoint
CREATE TYPE "public"."app_role" AS ENUM('admin', 'editor');--> statement-breakpoint
CREATE TYPE "public"."exam_board" AS ENUM('IBPS PO', 'IBPS Clerk', 'SBI PO', 'SBI Clerk', 'RBI Grade B');--> statement-breakpoint
CREATE TYPE "public"."exam_section" AS ENUM('Quantitative Aptitude', 'Reasoning Ability', 'English Language', 'General Awareness', 'Computer Aptitude');--> statement-breakpoint
CREATE TYPE "public"."content_status" AS ENUM('draft', 'in_review', 'published', 'retired');--> statement-breakpoint
CREATE TYPE "public"."flashcard_status" AS ENUM('draft', 'approved', 'rejected');--> statement-breakpoint
CREATE TYPE "public"."moderation_status" AS ENUM('not_required', 'pending', 'approved', 'rejected');--> statement-breakpoint
CREATE TYPE "public"."note_visibility" AS ENUM('private', 'unlisted', 'public');--> statement-breakpoint
CREATE TYPE "public"."attempt_mode" AS ENUM('bank', 'mix', 'paper');--> statement-breakpoint
CREATE TABLE "ai_usage" (
	"user_id" uuid NOT NULL,
	"feature" text NOT NULL,
	"day" date NOT NULL,
	"calls" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "ai_usage_user_id_feature_day_pk" PRIMARY KEY("user_id","feature","day")
);
--> statement-breakpoint
ALTER TABLE "ai_usage" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "entitlements" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "entitlements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"plan" "plan_key" NOT NULL,
	"access_until" timestamp with time zone NOT NULL,
	"status" "subscription_status" NOT NULL,
	"subscription_id" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "entitlements_user_id_key" UNIQUE("user_id")
);
--> statement-breakpoint
ALTER TABLE "entitlements" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "payment_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payment_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"event_id" text NOT NULL,
	"event_type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "payment_events_event_id_key" UNIQUE("event_id")
);
--> statement-breakpoint
ALTER TABLE "payment_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "payment_plans" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payment_plans_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"plan" "plan_key" NOT NULL,
	"interval" "billing_interval" NOT NULL,
	"currency" "currency_code" NOT NULL,
	"razorpay_plan_id" text NOT NULL,
	"amount_minor" integer NOT NULL,
	"list_amount_minor" integer,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "payment_plans_razorpay_plan_id_key" UNIQUE("razorpay_plan_id")
);
--> statement-breakpoint
ALTER TABLE "payment_plans" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "payments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"subscription_id" bigint,
	"razorpay_payment_id" text NOT NULL,
	"amount_minor" integer NOT NULL,
	"currency" "currency_code" NOT NULL,
	"status" text NOT NULL,
	"method" text,
	"captured_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "payments_razorpay_payment_id_key" UNIQUE("razorpay_payment_id")
);
--> statement-breakpoint
ALTER TABLE "payments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "subscriptions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "subscriptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"razorpay_subscription_id" text NOT NULL,
	"plan_id" bigint NOT NULL,
	"status" "subscription_status" NOT NULL,
	"current_period_end" timestamp with time zone,
	"cancelled_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "subscriptions_razorpay_subscription_id_key" UNIQUE("razorpay_subscription_id")
);
--> statement-breakpoint
ALTER TABLE "subscriptions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "doubt_stuck" (
	"doubt_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "doubt_stuck_doubt_id_user_id_pk" PRIMARY KEY("doubt_id","user_id")
);
--> statement-breakpoint
ALTER TABLE "doubt_stuck" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "doubts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"author_id" uuid NOT NULL,
	"section" "exam_section" NOT NULL,
	"topic" text NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"stuck_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "doubts_title_len_check" CHECK (char_length("doubts"."title") between 10 and 160),
	CONSTRAINT "doubts_body_len_check" CHECK (char_length("doubts"."body") between 20 and 4000)
);
--> statement-breakpoint
ALTER TABLE "doubts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "descriptive_markings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"task_id" text NOT NULL,
	"answer" text NOT NULL,
	"words" integer NOT NULL,
	"total" numeric(5, 2) NOT NULL,
	"out_of" numeric(5, 2) NOT NULL,
	"marking" jsonb NOT NULL,
	"model" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "descriptive_markings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "articles" (
	"article_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"source" "article_source" NOT NULL,
	"title" text NOT NULL,
	"summary" text DEFAULT '' NOT NULL,
	"url" text NOT NULL,
	"published_at" timestamp with time zone NOT NULL,
	"scope" "article_scope" NOT NULL,
	"content_hash" text NOT NULL,
	"status" "article_status" DEFAULT 'new' NOT NULL,
	"skip_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "articles_content_hash_unique" UNIQUE("content_hash")
);
--> statement-breakpoint
ALTER TABLE "articles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "questions" (
	"question_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"article_id" uuid,
	"extracted_day" date NOT NULL,
	"question_text" text NOT NULL,
	"options" jsonb NOT NULL,
	"answer" text NOT NULL,
	"explanation" text NOT NULL,
	"topic" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "questions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "generate_runs" (
	"run_id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"day" date,
	"planned" integer DEFAULT 0 NOT NULL,
	"published" integer DEFAULT 0 NOT NULL,
	"bodies_fetched" integer DEFAULT 0 NOT NULL,
	"skipped_thin" integer DEFAULT 0 NOT NULL,
	"skipped_non_english" integer DEFAULT 0 NOT NULL,
	"skipped_irrelevant" integer DEFAULT 0 NOT NULL,
	"rejected_irrelevant" integer DEFAULT 0 NOT NULL,
	"rejected_grounding" integer DEFAULT 0 NOT NULL,
	"errors" integer DEFAULT 0 NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finished_at" timestamp with time zone,
	"status" text DEFAULT 'running' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "generate_runs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "role_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "role_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"role" "app_role" NOT NULL,
	"permission" "app_permission" NOT NULL,
	CONSTRAINT "role_permissions_role_permission_key" UNIQUE("role","permission")
);
--> statement-breakpoint
ALTER TABLE "role_permissions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_roles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"role" "app_role" NOT NULL,
	CONSTRAINT "user_roles_user_id_role_key" UNIQUE("user_id","role")
);
--> statement-breakpoint
ALTER TABLE "user_roles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "profiles" (
	"id" uuid PRIMARY KEY NOT NULL,
	"display_name" text,
	"bio" text,
	"country" char(2) DEFAULT 'IN' NOT NULL,
	"school" text,
	"target_year" integer,
	"exam_board" "exam_board" DEFAULT 'IBPS PO' NOT NULL,
	"default_section" "exam_section" DEFAULT 'Quantitative Aptitude' NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "profiles_target_year_check" CHECK ("profiles"."target_year" is null or "profiles"."target_year" between 2000 and 2100)
);
--> statement-breakpoint
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "chapters" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"subject_id" uuid NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"position" integer NOT NULL,
	CONSTRAINT "chapters_subject_id_slug_key" UNIQUE("subject_id","slug")
);
--> statement-breakpoint
ALTER TABLE "chapters" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "content_assets" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"topic_id" uuid,
	"object_key" text NOT NULL,
	"bucket" text NOT NULL,
	"mime_type" text NOT NULL,
	"byte_size" bigint NOT NULL,
	"sha256" text NOT NULL,
	"alt_text" text,
	"license" text,
	"attribution" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "content_assets_object_key_unique" UNIQUE("object_key"),
	CONSTRAINT "content_assets_byte_size_check" CHECK ("content_assets"."byte_size" >= 0)
);
--> statement-breakpoint
ALTER TABLE "content_assets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "content_block_sources" (
	"block_id" uuid NOT NULL,
	"source_id" uuid NOT NULL,
	CONSTRAINT "content_block_sources_block_id_source_id_pk" PRIMARY KEY("block_id","source_id")
);
--> statement-breakpoint
ALTER TABLE "content_block_sources" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "content_blocks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"content_version_id" uuid NOT NULL,
	"stable_key" text NOT NULL,
	"type" text NOT NULL,
	"title" text NOT NULL,
	"body_markdown" text NOT NULL,
	"search_keywords" text[] DEFAULT '{}' NOT NULL,
	"position" integer NOT NULL,
	CONSTRAINT "content_blocks_content_version_id_stable_key_key" UNIQUE("content_version_id","stable_key")
);
--> statement-breakpoint
ALTER TABLE "content_blocks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "content_sources" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"registry_key" text,
	"url" text NOT NULL,
	"title" text NOT NULL,
	"publisher" text NOT NULL,
	"usage_mode" text NOT NULL,
	"license" text,
	"retrieved_at" timestamp with time zone NOT NULL,
	"source_updated_at" timestamp with time zone,
	"content_hash" text,
	"notes" text,
	CONSTRAINT "content_sources_url_retrieved_at_key" UNIQUE("url","retrieved_at")
);
--> statement-breakpoint
ALTER TABLE "content_sources" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "content_versions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"topic_id" uuid NOT NULL,
	"version" integer NOT NULL,
	"source_hash" text NOT NULL,
	"authored_by" text,
	"reviewed_by" text,
	"review_notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "content_versions_topic_id_version_key" UNIQUE("topic_id","version")
);
--> statement-breakpoint
ALTER TABLE "content_versions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "flashcards" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"topic_id" uuid NOT NULL,
	"content_version" integer NOT NULL,
	"stable_key" text NOT NULL,
	"front" text NOT NULL,
	"back" text NOT NULL,
	"explanation" text,
	"difficulty" text NOT NULL,
	"source_block_keys" text[] DEFAULT '{}' NOT NULL,
	"status" "flashcard_status" DEFAULT 'draft' NOT NULL,
	"position" integer NOT NULL,
	"generated_by" text,
	"reviewed_by" text,
	CONSTRAINT "flashcards_topic_id_content_version_stable_key_key" UNIQUE("topic_id","content_version","stable_key"),
	CONSTRAINT "flashcards_front_len_check" CHECK (char_length("flashcards"."front") <= 240),
	CONSTRAINT "flashcards_back_len_check" CHECK (char_length("flashcards"."back") <= 800),
	CONSTRAINT "flashcards_difficulty_check" CHECK ("flashcards"."difficulty" in ('easy','medium','hard'))
);
--> statement-breakpoint
ALTER TABLE "flashcards" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "study_progress" (
	"user_id" uuid NOT NULL,
	"topic_id" uuid NOT NULL,
	"progress_percent" integer DEFAULT 0 NOT NULL,
	"completed_at" timestamp with time zone,
	"last_opened_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "study_progress_user_id_topic_id_pk" PRIMARY KEY("user_id","topic_id"),
	CONSTRAINT "study_progress_percent_check" CHECK ("study_progress"."progress_percent" between 0 and 100)
);
--> statement-breakpoint
ALTER TABLE "study_progress" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "subjects" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"position" integer NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "subjects_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "subjects" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "topics" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"chapter_id" uuid NOT NULL,
	"slug" text NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"title" text NOT NULL,
	"summary" text NOT NULL,
	"difficulty" text NOT NULL,
	"estimated_minutes" integer NOT NULL,
	"exam_tags" text[] DEFAULT '{}' NOT NULL,
	"prerequisite_topic_slugs" text[] DEFAULT '{}' NOT NULL,
	"learning_objectives" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"tags" text[] DEFAULT '{}' NOT NULL,
	"status" "content_status" DEFAULT 'draft' NOT NULL,
	"current_version" integer DEFAULT 1 NOT NULL,
	"review_cadence_days" integer DEFAULT 365 NOT NULL,
	"last_reviewed_at" timestamp with time zone,
	"published_at" timestamp with time zone,
	CONSTRAINT "topics_chapter_id_slug_key" UNIQUE("chapter_id","slug"),
	CONSTRAINT "topics_difficulty_check" CHECK ("topics"."difficulty" in ('beginner','intermediate','advanced')),
	CONSTRAINT "topics_estimated_minutes_check" CHECK ("topics"."estimated_minutes" > 0)
);
--> statement-breakpoint
ALTER TABLE "topics" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_notes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"topic_id" uuid NOT NULL,
	"block_stable_key" text,
	"content_version" integer,
	"selected_text" text,
	"text_before" text,
	"text_after" text,
	"body_markdown" text NOT NULL,
	"color" text DEFAULT 'yellow' NOT NULL,
	"visibility" "note_visibility" DEFAULT 'private' NOT NULL,
	"moderation" "moderation_status" DEFAULT 'not_required' NOT NULL,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_notes_body_len_check" CHECK (char_length("user_notes"."body_markdown") <= 10000)
);
--> statement-breakpoint
ALTER TABLE "user_notes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "attempt_answers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attempt_answers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"attempt_id" bigint NOT NULL,
	"q_id" text NOT NULL,
	"chosen" char(1),
	"is_correct" boolean,
	"time_ms" integer,
	CONSTRAINT "attempt_answers_attempt_id_q_id_key" UNIQUE("attempt_id","q_id")
);
--> statement-breakpoint
ALTER TABLE "attempt_answers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "attempts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"mode" "attempt_mode" NOT NULL,
	"paper_id" text,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"submitted_at" timestamp with time zone,
	"score" numeric(6, 2),
	"served_q_ids" text[]
);
--> statement-breakpoint
ALTER TABLE "attempts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "bank_questions" (
	"q_id" text PRIMARY KEY NOT NULL,
	"paper_id" text NOT NULL,
	"q_num" integer NOT NULL,
	"stem" text NOT NULL,
	"options" jsonb NOT NULL,
	"answer" char(1),
	"explanation" text,
	"section" text,
	"topic" text,
	"difficulty" integer,
	"direction_id" text,
	"marks" numeric(4, 2) DEFAULT '1' NOT NULL,
	"negative_marks" numeric(4, 2) DEFAULT '0.25' NOT NULL,
	"content_hash" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "bank_questions_paper_id_q_num_key" UNIQUE("paper_id","q_num")
);
--> statement-breakpoint
ALTER TABLE "bank_questions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "directions" (
	"paper_id" text NOT NULL,
	"direction_id" text NOT NULL,
	"body" text NOT NULL,
	CONSTRAINT "directions_paper_id_direction_id_pk" PRIMARY KEY("paper_id","direction_id")
);
--> statement-breakpoint
ALTER TABLE "directions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "notes" (
	"note_id" text PRIMARY KEY NOT NULL,
	"section" text NOT NULL,
	"topic" text NOT NULL,
	"subtopic" text,
	"topic_title" text NOT NULL,
	"topic_order" integer NOT NULL,
	"subtopic_order" integer NOT NULL,
	"aliases" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"exam_relevance" jsonb NOT NULL,
	"title" text NOT NULL,
	"summary" text NOT NULL,
	"concept" text NOT NULL,
	"formulas" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"tricks" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"common_mistakes" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"worked_examples" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"related_question_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"difficulty" text,
	"sources" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"confirmations" integer,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"status" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "notes_section_topic_subtopic_key" UNIQUE("section","topic","subtopic")
);
--> statement-breakpoint
ALTER TABLE "notes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "papers" (
	"paper_id" text PRIMARY KEY NOT NULL,
	"bank" text,
	"role" text,
	"exam_type" text,
	"year" integer,
	"shift" text,
	"memory_based" boolean DEFAULT false NOT NULL,
	"exam_key" text NOT NULL,
	"is_canonical" boolean DEFAULT true NOT NULL,
	"duration_min" integer,
	"total_marks" integer,
	"section_timing" jsonb,
	"source_pdf" text,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
ALTER TABLE "papers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_topic_stats" (
	"user_id" uuid NOT NULL,
	"topic" text NOT NULL,
	"attempted" integer DEFAULT 0 NOT NULL,
	"correct" integer DEFAULT 0 NOT NULL,
	"last_seen_at" timestamp with time zone,
	CONSTRAINT "user_topic_stats_user_id_topic_pk" PRIMARY KEY("user_id","topic")
);
--> statement-breakpoint
ALTER TABLE "user_topic_stats" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "doubt_stuck" ADD CONSTRAINT "doubt_stuck_doubt_id_doubts_id_fk" FOREIGN KEY ("doubt_id") REFERENCES "public"."doubts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "doubt_stuck" ADD CONSTRAINT "doubt_stuck_user_id_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "doubts" ADD CONSTRAINT "doubts_author_id_profiles_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chapters" ADD CONSTRAINT "chapters_subject_id_subjects_id_fk" FOREIGN KEY ("subject_id") REFERENCES "public"."subjects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "content_assets" ADD CONSTRAINT "content_assets_topic_id_topics_id_fk" FOREIGN KEY ("topic_id") REFERENCES "public"."topics"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "content_block_sources" ADD CONSTRAINT "content_block_sources_block_id_content_blocks_id_fk" FOREIGN KEY ("block_id") REFERENCES "public"."content_blocks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "content_block_sources" ADD CONSTRAINT "content_block_sources_source_id_content_sources_id_fk" FOREIGN KEY ("source_id") REFERENCES "public"."content_sources"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "content_blocks" ADD CONSTRAINT "content_blocks_content_version_id_content_versions_id_fk" FOREIGN KEY ("content_version_id") REFERENCES "public"."content_versions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "content_versions" ADD CONSTRAINT "content_versions_topic_id_topics_id_fk" FOREIGN KEY ("topic_id") REFERENCES "public"."topics"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flashcards" ADD CONSTRAINT "flashcards_topic_id_topics_id_fk" FOREIGN KEY ("topic_id") REFERENCES "public"."topics"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "study_progress" ADD CONSTRAINT "study_progress_topic_id_topics_id_fk" FOREIGN KEY ("topic_id") REFERENCES "public"."topics"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "topics" ADD CONSTRAINT "topics_chapter_id_chapters_id_fk" FOREIGN KEY ("chapter_id") REFERENCES "public"."chapters"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_notes" ADD CONSTRAINT "user_notes_topic_id_topics_id_fk" FOREIGN KEY ("topic_id") REFERENCES "public"."topics"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempt_answers" ADD CONSTRAINT "attempt_answers_attempt_id_attempts_id_fk" FOREIGN KEY ("attempt_id") REFERENCES "public"."attempts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempt_answers" ADD CONSTRAINT "attempt_answers_q_id_bank_questions_q_id_fk" FOREIGN KEY ("q_id") REFERENCES "public"."bank_questions"("q_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempts" ADD CONSTRAINT "attempts_paper_id_papers_paper_id_fk" FOREIGN KEY ("paper_id") REFERENCES "public"."papers"("paper_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bank_questions" ADD CONSTRAINT "bank_questions_paper_id_papers_paper_id_fk" FOREIGN KEY ("paper_id") REFERENCES "public"."papers"("paper_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bank_questions" ADD CONSTRAINT "bank_questions_paper_id_direction_id_directions_paper_id_direction_id_fk" FOREIGN KEY ("paper_id","direction_id") REFERENCES "public"."directions"("paper_id","direction_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "directions" ADD CONSTRAINT "directions_paper_id_papers_paper_id_fk" FOREIGN KEY ("paper_id") REFERENCES "public"."papers"("paper_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ai_usage_user_day_idx" ON "ai_usage" USING btree ("user_id","day");--> statement-breakpoint
CREATE INDEX "payment_events_event_type_idx" ON "payment_events" USING btree ("event_type");--> statement-breakpoint
CREATE UNIQUE INDEX "payment_plans_active_slot_key" ON "payment_plans" USING btree ("plan","interval","currency") WHERE "payment_plans"."active";--> statement-breakpoint
CREATE INDEX "payments_user_id_idx" ON "payments" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "payments_subscription_id_idx" ON "payments" USING btree ("subscription_id");--> statement-breakpoint
CREATE INDEX "subscriptions_user_id_idx" ON "subscriptions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "doubt_stuck_user_idx" ON "doubt_stuck" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "doubts_stuck_idx" ON "doubts" USING btree ("section","stuck_count" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "doubts_created_idx" ON "doubts" USING btree ("section","created_at" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "doubts_author_idx" ON "doubts" USING btree ("author_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "descriptive_markings_user_idx" ON "descriptive_markings" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "articles_status_published_at_idx" ON "articles" USING btree ("status","published_at");--> statement-breakpoint
CREATE INDEX "articles_published_at_idx" ON "articles" USING btree ("published_at");--> statement-breakpoint
CREATE INDEX "questions_extracted_day_idx" ON "questions" USING btree ("extracted_day");--> statement-breakpoint
CREATE UNIQUE INDEX "questions_article_id_unique_idx" ON "questions" USING btree ("article_id");--> statement-breakpoint
CREATE INDEX "generate_runs_started_at_idx" ON "generate_runs" USING btree ("started_at");--> statement-breakpoint
CREATE INDEX "chapters_subject_id_idx" ON "chapters" USING btree ("subject_id");--> statement-breakpoint
CREATE INDEX "content_blocks_content_version_id_idx" ON "content_blocks" USING btree ("content_version_id");--> statement-breakpoint
CREATE INDEX "flashcards_topic_id_idx" ON "flashcards" USING btree ("topic_id");--> statement-breakpoint
CREATE INDEX "topics_chapter_id_idx" ON "topics" USING btree ("chapter_id");--> statement-breakpoint
CREATE UNIQUE INDEX "topics_slug_key" ON "topics" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "user_notes_owner_topic_idx" ON "user_notes" USING btree ("user_id","topic_id");--> statement-breakpoint
CREATE INDEX "attempt_answers_attempt_id_idx" ON "attempt_answers" USING btree ("attempt_id");--> statement-breakpoint
CREATE INDEX "attempts_user_id_idx" ON "attempts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "attempts_user_started_idx" ON "attempts" USING btree ("user_id","started_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "bank_questions_paper_id_direction_id_idx" ON "bank_questions" USING btree ("paper_id","direction_id");--> statement-breakpoint
CREATE INDEX "bank_questions_section_topic_idx" ON "bank_questions" USING btree ("section","topic");--> statement-breakpoint
CREATE INDEX "bank_questions_content_hash_idx" ON "bank_questions" USING btree ("content_hash");--> statement-breakpoint
CREATE INDEX "notes_section_topic_idx" ON "notes" USING btree ("section","topic");--> statement-breakpoint
CREATE INDEX "papers_exam_key_idx" ON "papers" USING btree ("exam_key");--> statement-breakpoint
CREATE INDEX "papers_filter_idx" ON "papers" USING btree ("bank","role","exam_type","year");--> statement-breakpoint
CREATE POLICY "signed-in users can read their own usage" ON "ai_usage" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "ai_usage"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can read their own entitlement" ON "entitlements" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "entitlements"."user_id");--> statement-breakpoint
CREATE POLICY "anyone can read plan prices" ON "payment_plans" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read their own payments" ON "payments" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "payments"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can read their own subscriptions" ON "subscriptions" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "subscriptions"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can read stuck marks" ON "doubt_stuck" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can mark themselves stuck" ON "doubt_stuck" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.uid()) = "doubt_stuck"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can clear their own stuck mark" ON "doubt_stuck" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((select auth.uid()) = "doubt_stuck"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can read every doubt" ON "doubts" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can post their own doubts" ON "doubts" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.uid()) = "doubts"."author_id");--> statement-breakpoint
CREATE POLICY "signed-in users can read their own markings" ON "descriptive_markings" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "descriptive_markings"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can read Gazette articles" ON "articles" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read Gazette questions" ON "questions" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read permissions" ON "role_permissions" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read their own role" ON "user_roles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "user_roles"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can read their own profile" ON "profiles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "profiles"."id");--> statement-breakpoint
CREATE POLICY "signed-in users can update their own profile" ON "profiles" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.uid()) = "profiles"."id") WITH CHECK ((select auth.uid()) = "profiles"."id");--> statement-breakpoint
CREATE POLICY "signed-in users can read chapters" ON "chapters" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read content assets" ON "content_assets" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read content block sources" ON "content_block_sources" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read content blocks" ON "content_blocks" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read content sources" ON "content_sources" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read content versions" ON "content_versions" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read flashcards" ON "flashcards" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "owners read their own progress" ON "study_progress" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "study_progress"."user_id");--> statement-breakpoint
CREATE POLICY "owners upsert their own progress" ON "study_progress" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.uid()) = "study_progress"."user_id");--> statement-breakpoint
CREATE POLICY "owners update their own progress" ON "study_progress" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.uid()) = "study_progress"."user_id") WITH CHECK ((select auth.uid()) = "study_progress"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can read subjects" ON "subjects" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read topics" ON "topics" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "owners read their own notes" ON "user_notes" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "user_notes"."user_id");--> statement-breakpoint
CREATE POLICY "owners create their own notes" ON "user_notes" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.uid()) = "user_notes"."user_id");--> statement-breakpoint
CREATE POLICY "owners update their own notes" ON "user_notes" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.uid()) = "user_notes"."user_id") WITH CHECK ((select auth.uid()) = "user_notes"."user_id");--> statement-breakpoint
CREATE POLICY "owners delete their own notes" ON "user_notes" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((select auth.uid()) = "user_notes"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can read their own attempt answers" ON "attempt_answers" AS PERMISSIVE FOR SELECT TO "authenticated" USING (exists (select 1 from attempts a where a.id = "attempt_answers"."attempt_id" and a.user_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "signed-in users can read their own attempts" ON "attempts" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "attempts"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can read directions" ON "directions" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read papers" ON "papers" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read their own topic stats" ON "user_topic_stats" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "user_topic_stats"."user_id");