CREATE TYPE "public"."app_permission" AS ENUM('questions.create', 'questions.update', 'questions.delete', 'papers.import', 'users.read');--> statement-breakpoint
CREATE TYPE "public"."app_role" AS ENUM('admin', 'editor');--> statement-breakpoint
CREATE TABLE "role_permissions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "role_permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"role" "app_role" NOT NULL,
	"permission" "app_permission" NOT NULL,
	CONSTRAINT "role_permissions_role_permission_key" UNIQUE("role","permission")
);
--> statement-breakpoint
ALTER TABLE "role_permissions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_roles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"role" "app_role" NOT NULL,
	CONSTRAINT "user_roles_user_id_role_key" UNIQUE("user_id","role")
);
--> statement-breakpoint
ALTER TABLE "user_roles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "signed-in users can read permissions" ON "role_permissions" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read their own role" ON "user_roles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "user_roles"."user_id");--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Everything below is hand-written: drizzle-kit cannot generate plpgsql
-- functions, grants, references into the Supabase-managed auth schema, or
-- seed rows. Keep additions here rather than in a separate file so the whole
-- role setup applies as one unit.
-- ---------------------------------------------------------------------------

-- Drizzle can't model a reference into auth.*, so the FK is added by hand.
ALTER TABLE "user_roles"
  ADD CONSTRAINT "user_roles_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES auth.users(id) ON DELETE CASCADE;
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "user_roles_user_id_idx" ON "user_roles" ("user_id");
--> statement-breakpoint

-- Postgres checks table GRANTs before RLS, so without this the "read your own
-- role" policy never runs and every lookup silently returns zero rows.
GRANT SELECT ON public.user_roles TO authenticated;
--> statement-breakpoint
GRANT SELECT ON public.role_permissions TO authenticated;
--> statement-breakpoint
REVOKE ALL ON public.user_roles FROM anon;
--> statement-breakpoint
REVOKE ALL ON public.role_permissions FROM anon;
--> statement-breakpoint

-- SECURITY DEFINER so these can read user_roles without tripping its own RLS.
-- search_path is pinned so a caller can't shadow the tables they resolve.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = (SELECT auth.uid()) AND role = 'admin'
  );
$$;
--> statement-breakpoint

-- Used by RLS on content tables: USING ((select authorize('questions.delete')))
CREATE OR REPLACE FUNCTION public.authorize(requested_permission public.app_permission)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles ur
    JOIN public.role_permissions rp ON rp.role = ur.role
    WHERE ur.user_id = (SELECT auth.uid())
      AND rp.permission = requested_permission
  );
$$;
--> statement-breakpoint

GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION public.authorize(public.app_permission) TO authenticated;
--> statement-breakpoint

INSERT INTO public.role_permissions (role, permission) VALUES
  ('admin',  'questions.create'),
  ('admin',  'questions.update'),
  ('admin',  'questions.delete'),
  ('admin',  'papers.import'),
  ('admin',  'users.read'),
  ('editor', 'questions.create'),
  ('editor', 'questions.update')
ON CONFLICT (role, permission) DO NOTHING;
--> statement-breakpoint

-- Grants the first admin by email. Inserts nothing if that account hasn't
-- signed up yet; re-run this statement after it has.
INSERT INTO public.user_roles (user_id, role)
SELECT id, 'admin' FROM auth.users WHERE email = 'onelystop@gmail.com'
ON CONFLICT (user_id, role) DO NOTHING;
