CREATE TYPE "public"."billing_interval" AS ENUM('monthly', 'yearly');--> statement-breakpoint
CREATE TYPE "public"."currency_code" AS ENUM('INR', 'USD');--> statement-breakpoint
CREATE TYPE "public"."plan_key" AS ENUM('pro', 'school');--> statement-breakpoint
CREATE TYPE "public"."subscription_status" AS ENUM('created', 'authenticated', 'active', 'pending', 'halted', 'cancelled', 'completed', 'expired');--> statement-breakpoint
CREATE TABLE "entitlements" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "entitlements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"plan" "plan_key" NOT NULL,
	"access_until" timestamp with time zone NOT NULL,
	"status" "subscription_status" NOT NULL,
	"subscription_id" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "entitlements_user_id_key" UNIQUE("user_id")
);
--> statement-breakpoint
ALTER TABLE "entitlements" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "payment_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payment_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"event_id" text NOT NULL,
	"event_type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "payment_events_event_id_key" UNIQUE("event_id")
);
--> statement-breakpoint
ALTER TABLE "payment_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "payment_plans" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payment_plans_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"plan" "plan_key" NOT NULL,
	"interval" "billing_interval" NOT NULL,
	"currency" "currency_code" NOT NULL,
	"razorpay_plan_id" text NOT NULL,
	"amount_minor" integer NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "payment_plans_razorpay_plan_id_key" UNIQUE("razorpay_plan_id")
);
--> statement-breakpoint
ALTER TABLE "payment_plans" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "payments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"subscription_id" bigint,
	"razorpay_payment_id" text NOT NULL,
	"amount_minor" integer NOT NULL,
	"currency" "currency_code" NOT NULL,
	"status" text NOT NULL,
	"method" text,
	"captured_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "payments_razorpay_payment_id_key" UNIQUE("razorpay_payment_id")
);
--> statement-breakpoint
ALTER TABLE "payments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "subscriptions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "subscriptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"razorpay_subscription_id" text NOT NULL,
	"plan_id" bigint NOT NULL,
	"status" "subscription_status" NOT NULL,
	"current_period_end" timestamp with time zone,
	"cancelled_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "subscriptions_razorpay_subscription_id_key" UNIQUE("razorpay_subscription_id")
);
--> statement-breakpoint
ALTER TABLE "subscriptions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE INDEX "payment_events_event_type_idx" ON "payment_events" USING btree ("event_type");--> statement-breakpoint
CREATE UNIQUE INDEX "payment_plans_active_slot_key" ON "payment_plans" USING btree ("plan","interval","currency") WHERE "payment_plans"."active";--> statement-breakpoint
CREATE INDEX "payments_user_id_idx" ON "payments" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "payments_subscription_id_idx" ON "payments" USING btree ("subscription_id");--> statement-breakpoint
CREATE INDEX "subscriptions_user_id_idx" ON "subscriptions" USING btree ("user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can read their own entitlement" ON "entitlements" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "entitlements"."user_id");--> statement-breakpoint
CREATE POLICY "anyone can read plan prices" ON "payment_plans" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read their own payments" ON "payments" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "payments"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can read their own subscriptions" ON "subscriptions" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "subscriptions"."user_id");
-- ---------------------------------------------------------------------------
-- Hand-written, as in 0000: drizzle-kit cannot generate references into the
-- Supabase-managed auth schema, grants, or check constraints. Kept in this file
-- so the billing tables apply as one unit.
-- ---------------------------------------------------------------------------

-- Deleting a user takes their billing history with them. The rows are useless
-- without the account, and leaving orphans behind is how a "which user owns
-- this payment" query starts returning nulls.
ALTER TABLE "subscriptions"
  ADD CONSTRAINT "subscriptions_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES auth.users(id) ON DELETE CASCADE;
--> statement-breakpoint

ALTER TABLE "payments"
  ADD CONSTRAINT "payments_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES auth.users(id) ON DELETE CASCADE;
--> statement-breakpoint

ALTER TABLE "entitlements"
  ADD CONSTRAINT "entitlements_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES auth.users(id) ON DELETE CASCADE;
--> statement-breakpoint

-- A subscription must name a plan that exists. RESTRICT rather than CASCADE:
-- deleting a plan someone is subscribed to should fail loudly, not quietly
-- delete their subscription.
ALTER TABLE "subscriptions"
  ADD CONSTRAINT "subscriptions_plan_id_fkey"
  FOREIGN KEY ("plan_id") REFERENCES public.payment_plans(id) ON DELETE RESTRICT;
--> statement-breakpoint

-- A payment may exist before we have matched it to a subscription -- the
-- authorisation charge can arrive on its own -- so this is nullable, and
-- clearing it must never delete the payment record.
ALTER TABLE "payments"
  ADD CONSTRAINT "payments_subscription_id_fkey"
  FOREIGN KEY ("subscription_id") REFERENCES public.subscriptions(id) ON DELETE SET NULL;
--> statement-breakpoint

-- Access outlives the subscription that bought it: a cancelled subscription
-- still leaves the user paid up to access_until.
ALTER TABLE "entitlements"
  ADD CONSTRAINT "entitlements_subscription_id_fkey"
  FOREIGN KEY ("subscription_id") REFERENCES public.subscriptions(id) ON DELETE SET NULL;
--> statement-breakpoint

-- Amounts are minor units and always positive. A zero or negative price is a
-- bug that would otherwise reach Razorpay as a real charge.
ALTER TABLE "payment_plans"
  ADD CONSTRAINT "payment_plans_amount_minor_positive" CHECK ("amount_minor" > 0);
--> statement-breakpoint

ALTER TABLE "payments"
  ADD CONSTRAINT "payments_amount_minor_positive" CHECK ("amount_minor" > 0);
--> statement-breakpoint

-- Postgres checks table GRANTs before RLS, so without these the SELECT policies
-- above never run and every lookup silently returns zero rows -- which for
-- entitlements reads as "this paying customer is not subscribed".
GRANT SELECT ON public.payment_plans TO anon, authenticated;
--> statement-breakpoint
GRANT SELECT ON public.subscriptions TO authenticated;
--> statement-breakpoint
GRANT SELECT ON public.payments TO authenticated;
--> statement-breakpoint
GRANT SELECT ON public.entitlements TO authenticated;
--> statement-breakpoint

-- No grant on payment_events at all: it holds raw provider payloads and has no
-- reason to be reachable from a browser session, policy or not.
REVOKE ALL ON public.payment_events FROM anon, authenticated;
--> statement-breakpoint

-- The reconciler asks "which subscriptions are due a charge we never saw", and
-- the alerting asks "whose access lapsed without a cancellation".
CREATE INDEX IF NOT EXISTS "subscriptions_status_idx" ON "subscriptions" ("status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "entitlements_access_until_idx" ON "entitlements" ("access_until");
