CREATE TABLE "exams" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "exams_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"bank" text NOT NULL,
	"role" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "exams_slug_key" UNIQUE("slug"),
	CONSTRAINT "exams_bank_role_key" UNIQUE("bank","role")
);
--> statement-breakpoint
ALTER TABLE "exams" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "profiles" (
	"id" uuid PRIMARY KEY NOT NULL,
	"display_name" text,
	"bio" text,
	"country" char(2) DEFAULT 'IN' NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_exam_targets" (
	"user_id" uuid NOT NULL,
	"exam_id" bigint NOT NULL,
	"target_year" integer NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	CONSTRAINT "user_exam_targets_user_id_exam_id_pk" PRIMARY KEY("user_id","exam_id")
);
--> statement-breakpoint
ALTER TABLE "user_exam_targets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE UNIQUE INDEX "user_exam_targets_one_primary_key" ON "user_exam_targets" USING btree ("user_id") WHERE "user_exam_targets"."is_primary";--> statement-breakpoint
CREATE POLICY "anyone can read the exam catalogue" ON "exams" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read their own profile" ON "profiles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "profiles"."id");--> statement-breakpoint
CREATE POLICY "signed-in users can update their own profile" ON "profiles" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.uid()) = "profiles"."id") WITH CHECK ((select auth.uid()) = "profiles"."id");--> statement-breakpoint
CREATE POLICY "signed-in users can read their own targets" ON "user_exam_targets" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "user_exam_targets"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can add their own targets" ON "user_exam_targets" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.uid()) = "user_exam_targets"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can update their own targets" ON "user_exam_targets" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.uid()) = "user_exam_targets"."user_id") WITH CHECK ((select auth.uid()) = "user_exam_targets"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can remove their own targets" ON "user_exam_targets" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((select auth.uid()) = "user_exam_targets"."user_id");
-- ---------------------------------------------------------------------------
-- Hand-written below: drizzle-kit cannot generate references into the
-- Supabase-managed auth schema, grants, plpgsql, or seed rows.
-- ---------------------------------------------------------------------------

-- The profile IS the auth user -- same id, cascading delete. Supabase's own
-- user-management guide is the source of this shape.
ALTER TABLE "profiles"
  ADD CONSTRAINT "profiles_id_fkey"
  FOREIGN KEY ("id") REFERENCES auth.users(id) ON DELETE CASCADE;
--> statement-breakpoint

ALTER TABLE "user_exam_targets"
  ADD CONSTRAINT "user_exam_targets_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES auth.users(id) ON DELETE CASCADE;
--> statement-breakpoint

-- RESTRICT, not CASCADE: retiring an exam sets exams.active = false. If
-- deleting one silently deleted every user's target for it, we would lose what
-- people told us they were preparing for.
ALTER TABLE "user_exam_targets"
  ADD CONSTRAINT "user_exam_targets_exam_id_fkey"
  FOREIGN KEY ("exam_id") REFERENCES public.exams(id) ON DELETE RESTRICT;
--> statement-breakpoint

-- Postgres checks table GRANTs before RLS, so without these the policies above
-- never run and every lookup returns zero rows -- which reads as "this user has
-- no profile" rather than as a permissions bug.
GRANT SELECT, UPDATE ON public.profiles TO authenticated;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_exam_targets TO authenticated;
--> statement-breakpoint
GRANT SELECT ON public.exams TO anon, authenticated;
--> statement-breakpoint

-- The catalogue is public; a profile is not.
REVOKE ALL ON public.profiles FROM anon;
--> statement-breakpoint
REVOKE ALL ON public.user_exam_targets FROM anon;
--> statement-breakpoint

-- updated_at does not maintain itself, and this is the first table a user
-- writes to directly -- the billing tables are all service-role writes.
CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;
--> statement-breakpoint

CREATE TRIGGER profiles_touch_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
--> statement-breakpoint

-- Every authenticated request assumes a profile row exists, so it is created
-- with the account rather than lazily. If this raises, signup fails -- which is
-- correct: a user with no profile is a user the app cannot render.
--
-- display_name comes from raw_user_meta_data, which the user controls. That is
-- acceptable for a name and for nothing else; no column on this table is ever
-- read to make an authorization decision.
--
-- country is left at its default here. The trigger cannot see the request host,
-- so the signup route sets it after the account exists.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (
    NEW.id,
    NULLIF(TRIM(COALESCE(NEW.raw_user_meta_data ->> 'full_name',
                         NEW.raw_user_meta_data ->> 'name', '')), '')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;
--> statement-breakpoint

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
--> statement-breakpoint

-- Backfill: accounts that signed up before this migration have no profile.
INSERT INTO public.profiles (id, display_name)
SELECT id,
       NULLIF(TRIM(COALESCE(raw_user_meta_data ->> 'full_name',
                            raw_user_meta_data ->> 'name', '')), '')
FROM auth.users
ON CONFLICT (id) DO NOTHING;
--> statement-breakpoint

-- The five exams the question bank holds papers for. bank and role are spelled
-- exactly as the question JSON spells them, because that pair is the join key --
-- any other spelling matches no questions. There is no display_name column:
-- bank || ' ' || role gives "IBPS PO", "SBI Clerk", "IBPS RRB" for all five.
--
-- sort_order is by how much we cover, most first, counted from the committed
-- batches (IBPS PO 3918 questions, SBI Clerk 3216, IBPS RRB 2642, SBI PO 2563,
-- IBPS Clerk 2021). Recount before reordering; do not guess.
INSERT INTO public.exams (slug, bank, role, sort_order) VALUES
  ('ibps-po',    'IBPS', 'PO',    1),
  ('sbi-clerk',  'SBI',  'Clerk', 2),
  ('ibps-rrb',   'IBPS', 'RRB',   3),
  ('sbi-po',     'SBI',  'PO',    4),
  ('ibps-clerk', 'IBPS', 'Clerk', 5)
ON CONFLICT (bank, role) DO NOTHING;
