CREATE TABLE "exams" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "exams_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"bank" text NOT NULL,
	"role" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "exams_slug_key" UNIQUE("slug"),
	CONSTRAINT "exams_bank_role_key" UNIQUE("bank","role")
);
--> statement-breakpoint
ALTER TABLE "exams" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "profiles" (
	"id" uuid PRIMARY KEY NOT NULL,
	"display_name" text,
	"bio" text,
	"country" char(2) DEFAULT 'IN' NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_exam_targets" (
	"user_id" uuid NOT NULL,
	"exam_id" bigint NOT NULL,
	"target_year" integer NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	CONSTRAINT "user_exam_targets_user_id_exam_id_pk" PRIMARY KEY("user_id","exam_id")
);
--> statement-breakpoint
ALTER TABLE "user_exam_targets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE UNIQUE INDEX "user_exam_targets_one_primary_key" ON "user_exam_targets" USING btree ("user_id") WHERE "user_exam_targets"."is_primary";--> statement-breakpoint
CREATE POLICY "anyone can read the exam catalogue" ON "exams" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read their own profile" ON "profiles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "profiles"."id");--> statement-breakpoint
CREATE POLICY "signed-in users can update their own profile" ON "profiles" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.uid()) = "profiles"."id") WITH CHECK ((select auth.uid()) = "profiles"."id");--> statement-breakpoint
CREATE POLICY "signed-in users can read their own targets" ON "user_exam_targets" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "user_exam_targets"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can add their own targets" ON "user_exam_targets" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.uid()) = "user_exam_targets"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can update their own targets" ON "user_exam_targets" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.uid()) = "user_exam_targets"."user_id") WITH CHECK ((select auth.uid()) = "user_exam_targets"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can remove their own targets" ON "user_exam_targets" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((select auth.uid()) = "user_exam_targets"."user_id");

-- Hand-written: drizzle-kit generates none of the below. Do not regenerate.

ALTER TABLE "profiles"
  ADD CONSTRAINT "profiles_id_fkey"
  FOREIGN KEY ("id") REFERENCES auth.users(id) ON DELETE CASCADE;
--> statement-breakpoint

ALTER TABLE "user_exam_targets"
  ADD CONSTRAINT "user_exam_targets_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES auth.users(id) ON DELETE CASCADE;
--> statement-breakpoint

-- RESTRICT: retire an exam with active = false; deleting one must not erase
-- what users told us they are preparing for.
ALTER TABLE "user_exam_targets"
  ADD CONSTRAINT "user_exam_targets_exam_id_fkey"
  FOREIGN KEY ("exam_id") REFERENCES public.exams(id) ON DELETE RESTRICT;
--> statement-breakpoint

-- Postgres checks GRANTs before RLS: without these the policies never run and
-- every lookup returns zero rows, reading as missing data rather than denial.
GRANT SELECT, UPDATE ON public.profiles TO authenticated;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_exam_targets TO authenticated;
--> statement-breakpoint
GRANT SELECT ON public.exams TO anon, authenticated;
--> statement-breakpoint
REVOKE ALL ON public.profiles FROM anon;
--> statement-breakpoint
REVOKE ALL ON public.user_exam_targets FROM anon;
--> statement-breakpoint

CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;
--> statement-breakpoint

CREATE TRIGGER profiles_touch_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
--> statement-breakpoint

-- display_name comes from user-writable metadata: fine for a name, and the
-- reason no column here is ever read to authorize.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (
    NEW.id,
    NULLIF(TRIM(COALESCE(NEW.raw_user_meta_data ->> 'full_name',
                         NEW.raw_user_meta_data ->> 'name', '')), '')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;
--> statement-breakpoint

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
--> statement-breakpoint

INSERT INTO public.profiles (id, display_name)
SELECT id,
       NULLIF(TRIM(COALESCE(raw_user_meta_data ->> 'full_name',
                            raw_user_meta_data ->> 'name', '')), '')
FROM auth.users
ON CONFLICT (id) DO NOTHING;
--> statement-breakpoint

-- sort_order is by coverage in the committed batches, most first.
INSERT INTO public.exams (slug, bank, role, sort_order) VALUES
  ('ibps-po',    'IBPS', 'PO',    1),
  ('sbi-clerk',  'SBI',  'Clerk', 2),
  ('ibps-rrb',   'IBPS', 'RRB',   3),
  ('sbi-po',     'SBI',  'PO',    4),
  ('ibps-clerk', 'IBPS', 'Clerk', 5)
ON CONFLICT (bank, role) DO NOTHING;
