CREATE TYPE "public"."attempt_mode" AS ENUM('bank', 'mix', 'paper');--> statement-breakpoint
CREATE TABLE "attempt_answers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attempt_answers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"attempt_id" bigint NOT NULL,
	"q_id" text NOT NULL,
	"chosen" char(1),
	"is_correct" boolean,
	"time_ms" integer,
	CONSTRAINT "attempt_answers_attempt_id_q_id_key" UNIQUE("attempt_id","q_id")
);
--> statement-breakpoint
ALTER TABLE "attempt_answers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "attempts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"mode" "attempt_mode" NOT NULL,
	"paper_id" text,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"submitted_at" timestamp with time zone,
	"score" numeric(6, 2)
);
--> statement-breakpoint
ALTER TABLE "attempts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "directions" (
	"paper_id" text NOT NULL,
	"direction_id" text NOT NULL,
	"body" text NOT NULL,
	CONSTRAINT "directions_paper_id_direction_id_pk" PRIMARY KEY("paper_id","direction_id")
);
--> statement-breakpoint
ALTER TABLE "directions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "papers" (
	"paper_id" text PRIMARY KEY NOT NULL,
	"bank" text,
	"role" text,
	"exam_type" text,
	"year" integer,
	"shift" text,
	"memory_based" boolean DEFAULT false NOT NULL,
	"exam_key" text NOT NULL,
	"is_canonical" boolean DEFAULT true NOT NULL,
	"duration_min" integer,
	"total_marks" integer,
	"section_timing" jsonb,
	"source_pdf" text,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
ALTER TABLE "papers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "questions" (
	"q_id" text PRIMARY KEY NOT NULL,
	"paper_id" text NOT NULL,
	"q_num" integer NOT NULL,
	"stem" text NOT NULL,
	"options" jsonb NOT NULL,
	"answer" char(1),
	"explanation" text,
	"section" text,
	"topic" text,
	"difficulty" integer,
	"direction_id" text,
	"marks" numeric(4, 2) DEFAULT '1' NOT NULL,
	"negative_marks" numeric(4, 2) DEFAULT '0.25' NOT NULL,
	"content_hash" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "questions_paper_id_q_num_key" UNIQUE("paper_id","q_num")
);
--> statement-breakpoint
ALTER TABLE "questions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_topic_stats" (
	"user_id" uuid NOT NULL,
	"topic" text NOT NULL,
	"attempted" integer DEFAULT 0 NOT NULL,
	"correct" integer DEFAULT 0 NOT NULL,
	"last_seen_at" timestamp with time zone,
	CONSTRAINT "user_topic_stats_user_id_topic_pk" PRIMARY KEY("user_id","topic")
);
--> statement-breakpoint
ALTER TABLE "user_topic_stats" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "attempt_answers" ADD CONSTRAINT "attempt_answers_attempt_id_attempts_id_fk" FOREIGN KEY ("attempt_id") REFERENCES "public"."attempts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempt_answers" ADD CONSTRAINT "attempt_answers_q_id_questions_q_id_fk" FOREIGN KEY ("q_id") REFERENCES "public"."questions"("q_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempts" ADD CONSTRAINT "attempts_paper_id_papers_paper_id_fk" FOREIGN KEY ("paper_id") REFERENCES "public"."papers"("paper_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "directions" ADD CONSTRAINT "directions_paper_id_papers_paper_id_fk" FOREIGN KEY ("paper_id") REFERENCES "public"."papers"("paper_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "questions" ADD CONSTRAINT "questions_paper_id_papers_paper_id_fk" FOREIGN KEY ("paper_id") REFERENCES "public"."papers"("paper_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "questions" ADD CONSTRAINT "questions_paper_id_direction_id_directions_paper_id_direction_id_fk" FOREIGN KEY ("paper_id","direction_id") REFERENCES "public"."directions"("paper_id","direction_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "attempt_answers_attempt_id_idx" ON "attempt_answers" USING btree ("attempt_id");--> statement-breakpoint
CREATE INDEX "attempts_user_id_idx" ON "attempts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "papers_exam_key_idx" ON "papers" USING btree ("exam_key");--> statement-breakpoint
CREATE INDEX "papers_filter_idx" ON "papers" USING btree ("bank","role","exam_type","year");--> statement-breakpoint
CREATE INDEX "questions_paper_id_direction_id_idx" ON "questions" USING btree ("paper_id","direction_id");--> statement-breakpoint
CREATE INDEX "questions_section_topic_idx" ON "questions" USING btree ("section","topic");--> statement-breakpoint
CREATE INDEX "questions_content_hash_idx" ON "questions" USING btree ("content_hash");--> statement-breakpoint
CREATE POLICY "signed-in users can read their own attempt answers" ON "attempt_answers" AS PERMISSIVE FOR SELECT TO "authenticated" USING (exists (select 1 from attempts a where a.id = "attempt_answers"."attempt_id" and a.user_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "signed-in users can write their own attempt answers" ON "attempt_answers" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (exists (select 1 from attempts a where a.id = "attempt_answers"."attempt_id" and a.user_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "signed-in users can read their own attempts" ON "attempts" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "attempts"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can start their own attempts" ON "attempts" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.uid()) = "attempts"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can update their own attempts" ON "attempts" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.uid()) = "attempts"."user_id") WITH CHECK ((select auth.uid()) = "attempts"."user_id");--> statement-breakpoint
CREATE POLICY "anyone can read directions" ON "directions" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "anyone can read papers" ON "papers" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "anyone can read questions" ON "questions" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read their own topic stats" ON "user_topic_stats" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "user_topic_stats"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can write their own topic stats" ON "user_topic_stats" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.uid()) = "user_topic_stats"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can update their own topic stats" ON "user_topic_stats" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.uid()) = "user_topic_stats"."user_id") WITH CHECK ((select auth.uid()) = "user_topic_stats"."user_id");

-- Hand-written: drizzle-kit generates none of the below. Do not regenerate.
--
-- Postgres checks table GRANTs before RLS, so without these the SELECT/INSERT/
-- UPDATE policies above never run and every query silently returns zero rows
-- (a read) or a permission-denied error (a write) instead of the RLS-scoped
-- result the policy intends. One statement per table -- a comma-separated
-- table list does not parse as multiple grants to policy-grants.test.ts, or
-- to Postgres either.
GRANT SELECT ON public.papers TO anon, authenticated;
--> statement-breakpoint
GRANT SELECT ON public.directions TO anon, authenticated;
--> statement-breakpoint
GRANT SELECT ON public.questions TO anon, authenticated;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE ON public.attempts TO authenticated;
--> statement-breakpoint
GRANT SELECT, INSERT ON public.attempt_answers TO authenticated;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE ON public.user_topic_stats TO authenticated;
