CREATE TYPE "public"."attempt_mode" AS ENUM('bank', 'mix', 'paper');--> statement-breakpoint
CREATE TABLE "attempt_answers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attempt_answers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"attempt_id" bigint NOT NULL,
	"q_id" text NOT NULL,
	"chosen" char(1),
	"is_correct" boolean,
	"time_ms" integer,
	CONSTRAINT "attempt_answers_attempt_id_q_id_key" UNIQUE("attempt_id","q_id")
);
--> statement-breakpoint
ALTER TABLE "attempt_answers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "attempts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"mode" "attempt_mode" NOT NULL,
	"paper_id" text,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"submitted_at" timestamp with time zone,
	"score" numeric(6, 2)
);
--> statement-breakpoint
ALTER TABLE "attempts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "bank_questions" (
	"q_id" text PRIMARY KEY NOT NULL,
	"paper_id" text NOT NULL,
	"q_num" integer NOT NULL,
	"stem" text NOT NULL,
	"options" jsonb NOT NULL,
	"answer" char(1),
	"explanation" text,
	"section" text,
	"topic" text,
	"difficulty" integer,
	"direction_id" text,
	"marks" numeric(4, 2) DEFAULT '1' NOT NULL,
	"negative_marks" numeric(4, 2) DEFAULT '0.25' NOT NULL,
	"content_hash" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "bank_questions_paper_id_q_num_key" UNIQUE("paper_id","q_num")
);
--> statement-breakpoint
ALTER TABLE "bank_questions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "directions" (
	"paper_id" text NOT NULL,
	"direction_id" text NOT NULL,
	"body" text NOT NULL,
	CONSTRAINT "directions_paper_id_direction_id_pk" PRIMARY KEY("paper_id","direction_id")
);
--> statement-breakpoint
ALTER TABLE "directions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "notes" (
	"note_id" text PRIMARY KEY NOT NULL,
	"section" text NOT NULL,
	"topic" text NOT NULL,
	"subtopic" text,
	"topic_title" text NOT NULL,
	"topic_order" integer NOT NULL,
	"subtopic_order" integer NOT NULL,
	"aliases" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"exam_relevance" jsonb NOT NULL,
	"title" text NOT NULL,
	"summary" text NOT NULL,
	"concept" text NOT NULL,
	"formulas" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"tricks" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"common_mistakes" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"worked_examples" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"related_question_ids" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"difficulty" text,
	"sources" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"confirmations" integer,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"status" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "notes_section_topic_subtopic_key" UNIQUE("section","topic","subtopic")
);
--> statement-breakpoint
ALTER TABLE "notes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "papers" (
	"paper_id" text PRIMARY KEY NOT NULL,
	"bank" text,
	"role" text,
	"exam_type" text,
	"year" integer,
	"shift" text,
	"memory_based" boolean DEFAULT false NOT NULL,
	"exam_key" text NOT NULL,
	"is_canonical" boolean DEFAULT true NOT NULL,
	"duration_min" integer,
	"total_marks" integer,
	"section_timing" jsonb,
	"source_pdf" text,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
ALTER TABLE "papers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user_topic_stats" (
	"user_id" uuid NOT NULL,
	"topic" text NOT NULL,
	"attempted" integer DEFAULT 0 NOT NULL,
	"correct" integer DEFAULT 0 NOT NULL,
	"last_seen_at" timestamp with time zone,
	CONSTRAINT "user_topic_stats_user_id_topic_pk" PRIMARY KEY("user_id","topic")
);
--> statement-breakpoint
ALTER TABLE "user_topic_stats" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "attempt_answers" ADD CONSTRAINT "attempt_answers_attempt_id_attempts_id_fk" FOREIGN KEY ("attempt_id") REFERENCES "public"."attempts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempt_answers" ADD CONSTRAINT "attempt_answers_q_id_bank_questions_q_id_fk" FOREIGN KEY ("q_id") REFERENCES "public"."bank_questions"("q_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempts" ADD CONSTRAINT "attempts_paper_id_papers_paper_id_fk" FOREIGN KEY ("paper_id") REFERENCES "public"."papers"("paper_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bank_questions" ADD CONSTRAINT "bank_questions_paper_id_papers_paper_id_fk" FOREIGN KEY ("paper_id") REFERENCES "public"."papers"("paper_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bank_questions" ADD CONSTRAINT "bank_questions_paper_id_direction_id_directions_paper_id_direction_id_fk" FOREIGN KEY ("paper_id","direction_id") REFERENCES "public"."directions"("paper_id","direction_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "directions" ADD CONSTRAINT "directions_paper_id_papers_paper_id_fk" FOREIGN KEY ("paper_id") REFERENCES "public"."papers"("paper_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "attempt_answers_attempt_id_idx" ON "attempt_answers" USING btree ("attempt_id");--> statement-breakpoint
CREATE INDEX "attempts_user_id_idx" ON "attempts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "bank_questions_paper_id_direction_id_idx" ON "bank_questions" USING btree ("paper_id","direction_id");--> statement-breakpoint
CREATE INDEX "bank_questions_section_topic_idx" ON "bank_questions" USING btree ("section","topic");--> statement-breakpoint
CREATE INDEX "bank_questions_content_hash_idx" ON "bank_questions" USING btree ("content_hash");--> statement-breakpoint
CREATE INDEX "notes_section_topic_idx" ON "notes" USING btree ("section","topic");--> statement-breakpoint
CREATE INDEX "papers_exam_key_idx" ON "papers" USING btree ("exam_key");--> statement-breakpoint
CREATE INDEX "papers_filter_idx" ON "papers" USING btree ("bank","role","exam_type","year");--> statement-breakpoint
CREATE POLICY "signed-in users can read their own attempt answers" ON "attempt_answers" AS PERMISSIVE FOR SELECT TO "authenticated" USING (exists (select 1 from attempts a where a.id = "attempt_answers"."attempt_id" and a.user_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "signed-in users can read their own attempts" ON "attempts" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "attempts"."user_id");--> statement-breakpoint
CREATE POLICY "signed-in users can read directions" ON "directions" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read papers" ON "papers" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "signed-in users can read their own topic stats" ON "user_topic_stats" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "user_topic_stats"."user_id");
--> statement-breakpoint
-- SELECT only and authenticated only, one statement per table: the app reads and writes these as the owner over DATABASE_URL, so any wider grant is PostgREST attack surface with no caller -- and bank_questions (it holds `answer`) and notes get none at all.
GRANT SELECT ON public.papers TO authenticated;
--> statement-breakpoint
GRANT SELECT ON public.directions TO authenticated;
--> statement-breakpoint
GRANT SELECT ON public.attempts TO authenticated;
--> statement-breakpoint
GRANT SELECT ON public.attempt_answers TO authenticated;
--> statement-breakpoint
GRANT SELECT ON public.user_topic_stats TO authenticated;