CREATE TYPE "public"."report_reason" AS ENUM('answer_wrong', 'wrong_section', 'text_broken', 'options_wrong', 'other');--> statement-breakpoint
CREATE TYPE "public"."report_status" AS ENUM('open', 'fixed', 'rejected');--> statement-breakpoint
CREATE TABLE "question_reports" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "question_reports_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"q_id" text NOT NULL,
	"user_id" uuid NOT NULL,
	"reason" "report_reason" NOT NULL,
	"note" text,
	"status" "report_status" DEFAULT 'open' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "question_reports_q_id_user_id_key" UNIQUE("q_id","user_id")
);
--> statement-breakpoint
ALTER TABLE "question_reports" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "question_reports" ADD CONSTRAINT "question_reports_q_id_bank_questions_q_id_fk" FOREIGN KEY ("q_id") REFERENCES "public"."bank_questions"("q_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "question_reports_status_created_idx" ON "question_reports" USING btree ("status","created_at");--> statement-breakpoint
CREATE POLICY "signed-in users can read their own reports" ON "question_reports" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "question_reports"."user_id");--> statement-breakpoint
-- Hand-written: auth.users is not in the drizzle model, so without this a deleted
-- account leaves its reports behind and closing an account stops erasing them.
ALTER TABLE "question_reports"
  ADD CONSTRAINT "question_reports_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES auth.users(id) ON DELETE CASCADE;
